name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ensure this triggers on main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Export static files
        run: next export  # Ensures the 'out' folder is created

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: out  # This tells GitHub to deploy the 'out' folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
