name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Make sure this is your main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build && next export  # Ensure 'out' folder is created

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2  # ✅ Correct action
        with:
          path: out  # Deploy 'out' folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2  # ✅ Correct action
