name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04  # Forces a fresh runner

    steps:
      - name: Force Clean Checkout  # Ensures no old artifacts exist
        uses: actions/checkout@v3
        with:
          clean: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Remove node_modules & package-lock.json (Force Fresh Install)
        run: rm -rf node_modules package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
